### ISSUE TITLE
Can't check for updates 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse.2#101] opened 2024-10-13 16:29 UTC
### Skin section

Other

### Current Behavior

![20241013_172648](https://github.com/user-attachments/assets/d02a13c5-3f5c-4676-9385-7211770be287)

Hey jurial I've noticed currently there isn't an option in addon browser to check for updates like this screen shot on the original fuse, could you possibly implement it back? Many thanks 

### Expected Behavior

Previously was able to check for updates manually 

### Steps To Reproduce

Open addon browser check updates 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Rinicko100** [comment] 2024-10-13 23:24
You can check for updates by clicking on any item in the Addon browser

**Comment by jurialmunkey** [comment] 2024-10-13 23:24
Duplicate of https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/100

I commented there.

**Closed as completed** 2024-10-13 23:24 UTC
Labels: bug
