### ISSUE TITLE
Focus issue with widgets when returning from info dialog

### ISSUE THREAD

**Issue by Beats24-7** [jurialmunkey/skin.arctic.fuse.2#519] opened 2024-12-31 20:01 UTC
### Skin section

Widgets

### Current Behavior

When playback of an item is complete and you return to the home screen, the skin loses focus of the correct / current widget row.
![IMG_20241231_165959](https://github.com/user-attachments/assets/82c8157b-1f58-4e1e-a435-742370fc65f7)

Focus always moves downards two rows somehow. The fanart and info section is still showing the correct item.

### Expected Behavior

The skin should focus on the current item in a widget, or if it's removed (when watched), on the nearest / next item.
![IMG_20241231_170020](https://github.com/user-attachments/assets/57b1e9d0-583f-4bdd-8899-2d4f02418873)

### Steps To Reproduce

I am using the classic main menu + detailed mode (widgets+information). I have tested several different view types including landscape (+detailed or no info), landscape(s), board, square, etc... 

Choose an item in a widget, finish playback and return to home screen.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2024-12-31 22:24
I believe this is the same issue as #341

It is a Kodi issue and not much the skin can do about it. Usually it is due to a widget above refreshing and no longer having items. See this comment for more details: https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/341#issuecomment-2466012895

It also happens in Estuary, it is just less likely because you can't control which widgets are used in Estuary.

**Comment by jurialmunkey** [comment] 2024-12-31 22:28
Duplicate of #341

**Comment by jurialmunkey** [comment] 2024-12-31 22:29
Closing to keep to one thread for the issue (and I've renamed the other issue title to make it clearer).

**Closed as not planned by jurialmunkey** 2024-12-31 22:28 UTC
Labels: bug
