### ISSUE TITLE
Bug Report: Chinese Characters Display Issue in Skin

### ISSUE THREAD

**Issue by sr1223sr** [jurialmunkey/skin.arctic.fuse.2#366] opened 2024-11-14 11:42 UTC
### Skin section

Fonts and Languages

### Current Behavior

Thank you for creating such an outstanding skin.

As a user of the Chinese language, I encountered a minor issue where some commonly used Chinese characters (not rare ones, but those that often appear in menus) are not displaying correctly. I’ve attached some screenshots for your reference.

I thought I’d let you know about this in case it’s something you’d like to address in a future update. Thank you again for your time and for your wonderful work.

### Expected Behavior

n/a

### Steps To Reproduce

1. set the interface to Chinese
![IMG_7203](https://github.com/user-attachments/assets/4c6041fe-64f4-4a8d-9252-a24f1b30bc7f)
![IMG_7202](https://github.com/user-attachments/assets/57937b2c-aef1-439f-8f6e-6380d0b2d29c)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Bindou01** [comment] 2024-11-14 12:42
Unless I'm mistaken, this bug is already described here:
https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/339

**Comment by jurialmunkey** [comment] 2024-11-14 13:25
Duplicate of https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/339

**Closed as completed by jurialmunkey** 2024-11-14 13:25 UTC
Labels: bug
