### ISSUE TITLE
Actors Info Sheet: Back key that does not go back

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse.2#418] opened 2024-11-24 22:23 UTC
### Skin section

Other

### Current Behavior

When you exit the actor information sheet, the interface does not take a step back, but closes everything.

![image](https://github.com/user-attachments/assets/e4ca4c35-8c80-44c9-a248-3b364f0b2c5e)

-> 

![image](https://github.com/user-attachments/assets/39323117-83f9-40c3-a084-cf983c09eb15)

### Expected Behavior

Go back a step, here:

![image](https://github.com/user-attachments/assets/0ad34a1b-6650-4986-8bcb-e3a7fc74b1e2)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Bindou01** [comment] 2024-11-24 22:52
I just read this: https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/64
I guess it's related and the answer is the same...

**Comment by jurialmunkey** [comment] 2024-11-24 22:59
Duplicate of #64

**Closed as not planned by jurialmunkey** 2024-11-24 22:59 UTC
Labels: duplicate
